web_bh/Areas/Admin/Controllers/MyAdminController.cs
#nullable disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using web_bh.Models;
using Newtonsoft.Json;

namespace web_bh.Areas_Admin_Controllers
{
    [Area("Admin")]
    public class MyAdminController : Controller
    {
        private readonly web_bhContext _context;

        public MyAdminController(web_bhContext context)
        {
            _context = context;
        }
        public IActionResult Index(){
            return View();
        }
        [HttpPost]
        public async Task<JsonResult> layThongKe(int thang, int nam)
        {
            bool isAdmin = HttpContext.Session.GetInt32("role") == 1? true: false;
            if(!isAdmin)
            {
                return Json(new {
                    message = "Bạn phải là admin mới sử dụng được chức năng này!",
                    position = "0"
                });
            }else
            {
                List<Order> orders = _context.Orders.Include(x => x.OrderDetails.OrderBy(p => p.Id)).ToList();
                List<Order> order = new List<Order>();
                foreach (Order item in orders)
                {
                    if(item.OrderDate.Year == nam){
                        if(item.OrderDate.Month == thang){
                            order.Add(item);
                        }
                    }
                }
                int soNgay = (int)DateTime.DaysInMonth(nam, thang);

                int[] arr = new int[soNgay];
                int[] doanhThu = new int[soNgay];

                for(int i = 0; i < soNgay ; i++){
                    arr[i] = 0;
                    doanhThu[i] = 0;
                    foreach (Order item in order)
                    {
                        if(item.OrderDate.Day == i+1){
                            arr[i]++;
                            foreach (var item_1 in item.OrderDetails.ToList())
                            {
                                doanhThu[i] += (int)item_1.TotalMoney;
                            }
                        }
                    }
                }
                return Json(new {
                    songay = soNgay,
                    donhang = arr,
                    doanhthu = doanhThu
                });
                

            }

        }
    }
   

}

web_bh/Controllers/CartController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using web_bh.Models;

namespace web_bh.Controllers;

public class CartController : Controller
{
    private readonly ILogger<CartController> _logger;
    private readonly CartContext _cartContext;
    private readonly web_bhContext _context;

    public CartController(ILogger<CartController> logger, CartContext cartContext, web_bhContext context)
    {
        _logger = logger;
        _cartContext = cartContext;
        _context = context;
    }

    public IActionResult Index()
    {
        int? idUser = HttpContext.Session.GetInt32("user");
        if(idUser == null)
        {
            return RedirectToAction("Index", "Home");
        }else
        {

            List<Product> list = new List<Product>();
            var itemCart = _cartContext.cart.carts.Where(p => p.id_user == idUser).FirstOrDefault();
            if(itemCart != null)
            {
                var listCart = itemCart.cartItems.ToList();
                foreach (var item in listCart)
                {
                    Product _tmp = _context.Products.Where(p => p.Id == item.id_product).FirstOrDefault();
                    if(_tmp != null)
                    {
                        list.Add(_tmp);
                    }
                }
                ViewData["cart"] = listCart;
            }else
            {
                ViewData["cart"] = null;
            }
            return View(list);
        }
    }
    [HttpPost]
    public async Task<JsonResult> RemoveProduct(int idProduct, int sl)
    {
        Product product = await _context.Products.Where(p => p.Id.Equals(idProduct)).FirstOrDefaultAsync();
        if(product == null)
        {
            return Json(new {
                message = "Không tìm thấy sản phẩm!",
                position = "0"
            });
        }
        int? idUser = HttpContext.Session.GetInt32("user");
        if(idUser == null)
        {
            return Json(new {
                message = "Bạn phải đăng nhập mới sử dụng được chức năng này!",
                position = "0"
            });
        }else
        {
            CartData item = new CartData()
            {
                id_user = (int)idUser,
                cartItems = new List<CartItem>()
                {
                    new CartItem()
                    {
                        id_product = idProduct,
                        quantity = sl
                    }
                }
            };
            _cartContext.Remove(item);
            if(_cartContext.WriteData())
            {
                return Json(new {
                    message = "Xoá sản phẩm khỏi giỏ hàng thành công!",
                    position = "1"
                });
            }else
            {
                return Json(new {
                    message = "Không thể xoá sản phẩm khỏi giỏ hàng",
                    position = "0"
                });
            }
            
        }
    }
    
    [HttpPost]
    public async Task<JsonResult> SubProduct(int idProduct)
    {
        Product product = await _context.Products.Where(p => p.Id.Equals(idProduct)).FirstOrDefaultAsync();
        if(product == null)
        {
            return Json(new {
                message = "Không tìm thấy sản phẩm!",
                position = "0"
            });
        }
        int? idUser = HttpContext.Session.GetInt32("user");
        if(idUser == null)
        {
            return Json(new {
                message = "Bạn phải đăng nhập mới sử dụng được chức năng này!",
                position = "0"
            });
        }else
        {
            CartData item = new CartData()
            {
                id_user = (int)idUser,
                cartItems = new List<CartItem>()
                {
                    new CartItem()
                    {
                        id_product = idProduct,
                        quantity = 1
                    }
                }
            };
            _cartContext.Remove(item);
            if(_cartContext.WriteData())
            {
                return Json(new {
                    message = "Bớt 1 sản phẩm!",
                    position = "1"
                });
            }else
            {
                return Json(new {
                    message = "Không thể bớt 1 sản phẩm",
                    position = "0"
                });
            }
            
        }
    }
    
    [HttpPost]
    public async Task<JsonResult> AddProduct(int idProduct)
    {
        Product product = await _context.Products.Where(p => p.Id.Equals(idProduct)).FirstOrDefaultAsync();
        if(product == null)
        {
            return Json(new {
                message = "Không tìm thấy sản phẩm!",
                position = "0"
            });
        }
        int? idUser = HttpContext.Session.GetInt32("user");
        if(idUser == null)
        {
            return Json(new {
                message = "Bạn phải đăng nhập mới sử dụng được chức năng này!",
                position = "0"
            });
        }else
        {
            CartData item = new CartData()
            {
                id_user = (int)idUser,
                cartItems = new List<CartItem>()
                {
                    new CartItem()
                    {
                        id_product = idProduct,
                        quantity = 1
                    }
                }
            };
            _cartContext.Add(item);
            if(_cartContext.WriteData())
            {
                return Json(new {
                    message = "Thêm 1 sản phẩm!",
                    position = "1"
                });
            }else
            {
                return Json(new {
                    message = "Không thể thêm 1 sản phẩm!",
                    position = "0"
                });
            }
            
        }
    }
    
    [HttpPost]
    public async Task<JsonResult> addToCart(int idProduct, int sl = 1)
    {
        Product product = await _context.Products.Where(p => p.Id.Equals(idProduct)).FirstOrDefaultAsync();
        if(product == null)
        {
            return Json(new {
                message = "Không tìm thấy sản phẩm!",
                position = "0"
            });
        }
        int? idUser = HttpContext.Session.GetInt32("user");
        if(idUser == null)
        {
            return Json(new {
                message = "Bạn phải đăng nhập mới sử dụng được chức năng này!",
                position = "0"
            });
        }else
        {
            int sl_ = _cartContext.getQuantity((int)idUser, idProduct) + sl;
            if( sl_ > product.Quantity)
            {
                return Json(new {
                message = "Số lượng sản phẩm bạn đặt đã đạt tối đa!",
                position = "0"
            });
            }

            CartData item = new CartData()
            {
                id_user = (int)idUser,
                cartItems = new List<CartItem>()
                {
                    new CartItem()
                    {
                        id_product = idProduct,
                        quantity = sl
                    }
                }
            };
            _cartContext.Add(item);
            if(_cartContext.WriteData())
            {
                return Json(new {
                    message = "Thêm sản phẩm vào giỏ hàng thành công!",
                    position = "1"
                });
            }else
            {
                return Json(new {
                    message = "Không thể thêm sản phẩm vào giỏ hàng",
                    position = "0"
                });
            }
        }
    } 

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

web_bh/Controllers/ContacController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using System.IO;
using web_bh.Models;
using Newtonsoft.Json;

namespace web_bh.Controllers
{
    public class ContacController : Controller
    {
        private IWebHostEnvironment _hostEnvironment;
        private CartContext _cartContext;

        public ContacController (IWebHostEnvironment hostEnvironment, CartContext cartContext)
        {
            _hostEnvironment = hostEnvironment;
            _cartContext = cartContext;
        }
        public IActionResult Index()
        {
            return View();
        }
    }
}

web_bh/Controllers/ProductController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using web_bh.Models;

namespace web_bh.Controllers;

public class ProductController : Controller
{
    private readonly ILogger<ProductController> _logger;
    private readonly web_bhContext _context;

    public ProductController(ILogger<ProductController> logger, web_bhContext context)
    {
        _logger = logger;
        _context = context;
    }

    public IActionResult Index(int? id, int p = 1)
    {
        int size = 5;
        ViewData["IsCate"] = 0;
        if(id == null && id != 0)
        {   
            ViewData["Title"] = "Sản phẩm";
            var list = from a in _context.Products
                    join b in _context.Categories on a.IdCategory equals b.Id
                    select new {
                        id = a.Id,
                        idCate = b.Id,
                        nameCate = b.Name,
                        title = a.Title,
                        price = a.Price,
                        thumb = a.Thumbnail,
                        description = a.Description,
                        quantity = a.Quantity 
                    };
            ViewData["sl"] = (int)list.Count();
            int pages = (int)Math.Ceiling((double)list.Count() / size);
            ViewData["num_page"] = pages;
            ViewData["page"] = p;
            ViewData["ls_product"] = list.Skip((p - 1) * size).Take(size);
        }
        else
        {
            var rs = (from a in _context.Categories where a.Id == id select a).FirstOrDefault();
            if(rs == null)
                return NotFound();
            ViewData["Title"] = rs?.Name;
            ViewData["IsCate"] = rs?.Id;
            var list = from a in _context.Products
                    join b in _context.Categories on a.IdCategory equals b.Id
                    where b.Id == id
                    select new {
                        id = a.Id,
                        idCate = b.Id,
                        nameCate = b.Name,
                        title = a.Title,
                        price = a.Price,
                        thumb = a.Thumbnail,
                        description = a.Description,
                        quantity = a.Quantity 
                    };
            ViewData["sl"] = (int)list.Count();
            int pages = (int)Math.Ceiling((double)list.Count() / size);
            ViewData["num_page"] = pages;
            ViewData["page"] = p;
            ViewData["ls_product"] = list.Skip((p - 1) * size).Take(size);
        }
        return View();
    }

    public IActionResult Details(int? id)
    {
        if(id == null )
        {
            return NotFound();
        }
        else
        {
            var product = (from a in _context.Products where a.Id == id
                                    select a).FirstOrDefault();
            if(product == null)
                return NotFound();
            var rs = from a in _context.Categories where a.Id == product.IdCategory select a;
            if(!rs.Any())
                return NotFound();
            Category? category = rs.FirstOrDefault();
            ViewData["cate"] = category;
            return View(product);
        }
    }

    public IActionResult Search(string? q, int p = 1)
    {
        int size = 5;
        if(q == null)
        {
            ViewData["Title"] = "Tất cả";
            ViewData["IsCate"] = 0;
            var list = from a in _context.Products
                        join b in _context.Categories on a.IdCategory equals b.Id
                        select new {
                            id = a.Id,
                            idCate = b.Id,
                            nameCate = b.Name,
                            title = a.Title,
                            price = a.Price,
                            thumb = a.Thumbnail,
                            description = a.Description,
                            quantity = a.Quantity 
                        };
            ViewData["sl"] = (int)list.Count();
            int pages = (int)Math.Ceiling((double)list.Count() / size);
            ViewData["num_page"] = pages;
            ViewData["page"] = p;
            ViewData["ls_product"] = list.Skip((p - 1) * size).Take(size);
        }
        else
        {
            ViewData["Title"] = q;
            ViewData["IsCate"] = 1;
            ViewData["IsSearch"] = 1;
            var list = from a in _context.Products
                        join b in _context.Categories on a.IdCategory equals b.Id
                        where a.Title.ToLower().Contains(q.ToLower())
                        select new {
                            id = a.Id,
                            idCate = b.Id,
                            nameCate = b.Name,
                            title = a.Title,
                            price = a.Price,
                            thumb = a.Thumbnail,
                            description = a.Description,
                            quantity = a.Quantity 
                        };
            ViewData["sl"] = (int)list.Count();
                int pages = (int)Math.Ceiling((double)list.Count() / size);
                ViewData["num_page"] = pages;
                ViewData["page"] = p;
                ViewData["ls_product"] = list.Skip((p - 1) * size).Take(size);
        }
        return View("Index");
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

web_bh/Views/Shared/_FirstLayout.cshtml
@using Newtonsoft.Json
@inject web_bhContext dbContext
@inject CartContext cartContext
@inject Microsoft.AspNetCore.Http.IHttpContextAccessor HttpContextAccessor
@{
  List<Category> catergory_ls = dbContext.Categories.ToList();
  bool isLogin = false;
  int numCart = 0;
  User user = new User();
  if(HttpContextAccessor.HttpContext.Session.GetInt32("user") != null){
    int? idUser = (Int32)HttpContextAccessor.HttpContext.Session.GetInt32("user");
    var cart = cartContext.getCartData((int)idUser);
    foreach(var item in cart.cartItems.ToList())
    {
      numCart += item.quantity;
    }
    @* numCart = cart.cartItems.Count(); *@
    user = dbContext.Users.Where(p => p.Id.Equals(idUser)).FirstOrDefault();
    isLogin = true;
  }
}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />


  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
<!-- Nhúng các file css cho trang web -->
  <link rel="stylesheet" href="~/css/main.css" />

  @await RenderSectionAsync("css", required: false)

<!--  -->
  <title>@ViewData["Title"] | Cận GEAR</title>
</head>

<body>
@if(isLogin){
    
  <div class="account" id="repass">
    <div>
      <div></div>
      <button class="btn btn-strest" onclick="hideRepass()">x</button>
    </div>
    <form>
      <h1>Đổi mật khẩu</h1>
      <input type="password" placeholder="Nhập mật khẩu cũ" id="old_pass">
      <input type="password" placeholder="Nhập mật khẩu mới" id="new_pass">
      <input type="password" placeholder="Nhập lại mật khẩu mới" id="renew_pass">
      <input type="button" id="repass_submit" class="btn btn-green" value="Đổi mật khẩu">
    </form>
  </div>
}else
{
  <div class="account" id="login">
    <div>
      <div></div>
      <button class="btn btn-strest" onclick="hideLogin()">x</button>
    </div>
    <form>
      <h1>Đăng nhập</h1>
      <input type="text" placeholder="Tài khoản" id="login_name">
      <input type="password" placeholder="*******" id="login_pass">
      <div>
        <input id="login_checkSave" type="checkbox"><label for="checkSave">Lưu đăng nhập</label>
      </div>
      <input type="button" id="login_submit" class="btn btn-green" value="Đăng nhập">
    </form>
  </div>
  <div class="account" id="register">
    <div>
      <div></div>
      <button class="btn btn-strest" onclick="hideRegister()">x</button>
    </div>
    <form>
      <h1>Register</h1>
      <input type="text" placeholder="Tài khoản" id="register_name">
      <input type="password" placeholder="Mật khẩu" id="register_pass">
      <input type="password" placeholder="Nhập lại mật khẩu" id="register_repass">
      <input type="text" placeholder="Họ tên" id="register_fullname">
      <input type="text" placeholder="Số điện thoại" id="register_sdt">
      <input type="text" placeholder="Email" id="register_email">
      <input type="button" id="register_submit" class="btn btn-green" value="Đăng ký">
    </form>
  </div>
}
  <button id="btn_go_to_top">Top</button>
@if(isLogin){
  <a asp-controller="Cart" asp-action="Index" class="btn__cart">
    <img src="~/img/cart.png" alt="">
    <span>@numCart</span>
  </a>
}
<!-- Bắt đầu phần menu header -->
        <label class="btn btn-menu-m" for="check-menu-m">=</label>
  <nav class="header">
      <a asp-controller="Home" asp-action="Index">
          <img src="~/img/logo_3.gif" alt="">
      </a>
    <div class="header__right">
      <div>
        <a class="home-item" asp-controller="Home" asp-action="Index">Trang chủ</a>
        <span></span>
      </div>
      <div id="list-category">
        <a>Danh mục</a>
        <span></span>
        <div class="header__list">
          <ul>
            <li>
              <a asp-controller="Product" asp-action="Index">Tất cả</a>
              <span></span>
            </li>
          @foreach (var item in catergory_ls)
          { 
            <li>
              <a href="/Product?id=@item.Id">@item.Name</a>
              <span></span>
            </li>
          }
          </ul>
        </div>
      </div>
      <div>
        <a class="contact-item" asp-controller="Contac" asp-action="Index">Liên hệ</a>
        <span></span>
      </div>
      <div id="list-account">
        @if(isLogin){
          <a>@user.DisName</a>
        }else{
          <a>Tài khoản</a>
        }
        <span></span>
        <div class="header__list">
          <ul>
          @if(!isLogin){
            <li>
              <a onclick="showLogin()">Đăng nhập</a>
              <span></span>
            </li>
            <li>
              <a onclick="showRegister()">Đăng ký</a>
              <span></span>
            </li>
          }else
          {
            <li>
              <a asp-controller="Cart" asp-action="Index">Giỏ hàng</a>
              <span></span>
            </li>
            <li>
              <a asp-controller="MyOrder" asp-action="Index">Đơn hàng</a>
              <span></span>
            </li>
            <li>
              <a onclick="showRepass()">Đổi mật khẩu</a>
              <span></span>
            </li>
            <li>
              <a href="/Home/Logout">Đăng xuất</a>
              <span></span>
            </li>
          }
        @if(isLogin){
          if(user.IdRole == 1){
          <li>
            <a asp-area="Admin" asp-controller="MyAdmin" asp-action="Index">Quản trị</a>
            <span></span>
          </li>
          }
        }
          </ul>
        </div>
      </div>
      <div id="list-search">
        <a>Tìm kiếm</a>
        <span></span>
        <form action="/Product/Search" class="header__search" method="get">
          <input class="search__content" type="text" name="q" maxlength="200">
          <input type="submit" value="Tìm">
        </form>
      </div>
    </div>
  </nav>
<!-- Kết thúc phần menu header -->
<!-- Mở đầu phần menu mobile -->
    <input type="checkbox" id="check-menu-m">
    <div class="menu-m">
        <div>
            <a href="/">Trang chủ</a>
        </div>
        <div id="list-category-m">
            <a>Danh mục</a>
            <div class="header__list-m">
              <ul>
                <li>
                  <a asp-controller="Product" asp-action="Index">Tất cả</a>
                </li>
              @foreach (var item in catergory_ls)
              { 
                <li>
                  <a href="/Product?id=@item.Id">@item.Name</a>
                </li>
              }
              </ul>
            </div>
        </div>
        <div>
            <a href="/Contac">Liên hệ</a>
        </div>
    </div>
    <form action="/Product/Search" class="search-m" method="get">
        <input class="search__content" placeholder="Tìm kiếm trên shop" type="text" name="q" maxlength="200">
        <input type="submit" value="Tìm">
    </form>
<!-- Kết thúc phần menu mobile -->
<!-- Mở đầu phần nội dung trang web -->
  <div class="container">
    @RenderBody()
  </div>
<!-- Kết thúc phần nội dung trang web -->

<!-- Mở đầu phần footer -->
  <footer class="footer">
    <div class="footer__item">
      <h2>Giới thiệu</h2>
      <p>Website chuyên cung cấp các phụ kiện máy tính</p>
    </div>
    <div class="footer__item">
      <h2>Sản phẩm</h2>
      <div>
          @foreach (var item in catergory_ls)
          { 
        <a href="/Product?id=@item.Id">@item.Name</a>
          }
      </div>
    </div>
    <div class="footer__item">
      <h2>Liên hệ</h2>
      <div>
        <p>Địa chỉ: <a href="https://goo.gl/maps/C8Q69RJWWofJnb2m9" target="_blank">170 An Dương Vương, TP Quy Nhơn, Bình Định</a></p>
        <p>SĐT: <a href="tel:0987654321">0987654321</a></p>
        <p>Fanpage: <a href="https://www.facebook.com/dhquynhon" target="_blank">https://www.facebook.com/dhquynhon</a></p>
      </div>
    </div>
  </footer>
<!-- Kết thúc phần footer -->
  <!-- Nhúng các file javascript -->
  <script src="~/js/script.js"></script>
  <script src="~/js/index.js"></script>
  @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

web_bh/Views/Shared/_Layout.cshtml
@inject Microsoft.AspNetCore.Http.IHttpContextAccessor HttpContextAccessor
@{
    bool isAdmin = HttpContextAccessor.HttpContext.Session.GetInt32("role") == 1? true: false;
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Admin</title>
    
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/web_bh.styles.css" asp-append-version="true" />
</head>
<body>
    @if(isAdmin)
{

    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="Admin" asp-controller="MyAdmin" asp-action="Index"><h4>Trang quản trị</h4></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Admin" asp-controller="MyAdmin" asp-action="Index">HomeAdmin</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Admin" asp-controller="ProductManager" asp-action="Index">Sản phẩm</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Admin" asp-controller="CategoryManager" asp-action="Index">Danh mục</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Admin" asp-controller="OrderManager" asp-action="Index">Đơn hàng</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Về trang bán hàng</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
        </div>
    </footer>
}else
{
    <h1>Bạn không có quyền truy cập vào nội dung này!</h1>
    RenderBody();
}
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>