web_bh/Controllers/CartController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using web_bh.Models;

namespace web_bh.Controllers;

public class CartController : Controller
{
    private readonly ILogger<CartController> _logger;
    private readonly CartContext _cartContext;
    private readonly web_bhContext _context;

    public CartController(ILogger<CartController> logger, CartContext cartContext, web_bhContext context)
    {
        _logger = logger;
        _cartContext = cartContext;
        _context = context;
    }

    public IActionResult Index()
    {
        int? idUser = HttpContext.Session.GetInt32("user");
        if(idUser == null)
        {
            return RedirectToAction("Index", "Home");
        }else
        {

            List<Product> list = new List<Product>();
            var itemCart = _cartContext.cart.carts.Where(p => p.id_user == idUser).FirstOrDefault();
            if(itemCart != null)
            {
                var listCart = itemCart.cartItems.ToList();
                foreach (var item in listCart)
                {
                    Product _tmp = _context.Products.Where(p => p.Id == item.id_product).FirstOrDefault();
                    if(_tmp != null)
                    {
                        list.Add(_tmp);
                    }
                }
                ViewData["cart"] = listCart;
            }else
            {
                ViewData["cart"] = null;
            }
            return View(list);
        }
    }
    [HttpPost]
    public async Task<JsonResult> RemoveProduct(int idProduct, int sl)
    {
        Product product = await _context.Products.Where(p => p.Id.Equals(idProduct)).FirstOrDefaultAsync();
        if(product == null)
        {
            return Json(new {
                message = "Không tìm thấy sản phẩm!",
                position = "0"
            });
        }
        int? idUser = HttpContext.Session.GetInt32("user");
        if(idUser == null)
        {
            return Json(new {
                message = "Bạn phải đăng nhập mới sử dụng được chức năng này!",
                position = "0"
            });
        }else
        {
            CartData item = new CartData()
            {
                id_user = (int)idUser,
                cartItems = new List<CartItem>()
                {
                    new CartItem()
                    {
                        id_product = idProduct,
                        quantity = sl
                    }
                }
            };
            _cartContext.Remove(item);
            if(_cartContext.WriteData())
            {
                return Json(new {
                    message = "Xoá sản phẩm khỏi giỏ hàng thành công!",
                    position = "1"
                });
            }else
            {
                return Json(new {
                    message = "Không thể xoá sản phẩm khỏi giỏ hàng",
                    position = "0"
                });
            }
            
        }
    }
    
    [HttpPost]
    public async Task<JsonResult> SubProduct(int idProduct)
    {
        Product product = await _context.Products.Where(p => p.Id.Equals(idProduct)).FirstOrDefaultAsync();
        if(product == null)
        {
            return Json(new {
                message = "Không tìm thấy sản phẩm!",
                position = "0"
            });
        }
        int? idUser = HttpContext.Session.GetInt32("user");
        if(idUser == null)
        {
            return Json(new {
                message = "Bạn phải đăng nhập mới sử dụng được chức năng này!",
                position = "0"
            });
        }else
        {
            CartData item = new CartData()
            {
                id_user = (int)idUser,
                cartItems = new List<CartItem>()
                {
                    new CartItem()
                    {
                        id_product = idProduct,
                        quantity = 1
                    }
                }
            };
            _cartContext.Remove(item);
            if(_cartContext.WriteData())
            {
                return Json(new {
                    message = "Bớt 1 sản phẩm!",
                    position = "1"
                });
            }else
            {
                return Json(new {
                    message = "Không thể bớt 1 sản phẩm",
                    position = "0"
                });
            }
            
        }
    }
    
    [HttpPost]
    public async Task<JsonResult> AddProduct(int idProduct)
    {
        Product product = await _context.Products.Where(p => p.Id.Equals(idProduct)).FirstOrDefaultAsync();
        if(product == null)
        {
            return Json(new {
                message = "Không tìm thấy sản phẩm!",
                position = "0"
            });
        }
        int? idUser = HttpContext.Session.GetInt32("user");
        if(idUser == null)
        {
            return Json(new {
                message = "Bạn phải đăng nhập mới sử dụng được chức năng này!",
                position = "0"
            });
        }else
        {
            CartData item = new CartData()
            {
                id_user = (int)idUser,
                cartItems = new List<CartItem>()
                {
                    new CartItem()
                    {
                        id_product = idProduct,
                        quantity = 1
                    }
                }
            };
            _cartContext.Add(item);
            if(_cartContext.WriteData())
            {
                return Json(new {
                    message = "Thêm 1 sản phẩm!",
                    position = "1"
                });
            }else
            {
                return Json(new {
                    message = "Không thể thêm 1 sản phẩm!",
                    position = "0"
                });
            }
            
        }
    }
    
    [HttpPost]
    public async Task<JsonResult> addToCart(int idProduct, int sl = 1)
    {
        Product product = await _context.Products.Where(p => p.Id.Equals(idProduct)).FirstOrDefaultAsync();
        if(product == null)
        {
            return Json(new {
                message = "Không tìm thấy sản phẩm!",
                position = "0"
            });
        }
        int? idUser = HttpContext.Session.GetInt32("user");
        if(idUser == null)
        {
            return Json(new {
                message = "Bạn phải đăng nhập mới sử dụng được chức năng này!",
                position = "0"
            });
        }else
        {
            int sl_ = _cartContext.getQuantity((int)idUser, idProduct) + sl;
            if( sl_ > product.Quantity)
            {
                return Json(new {
                message = "Số lượng sản phẩm bạn đặt đã đạt tối đa!",
                position = "0"
            });
            }

            CartData item = new CartData()
            {
                id_user = (int)idUser,
                cartItems = new List<CartItem>()
                {
                    new CartItem()
                    {
                        id_product = idProduct,
                        quantity = sl
                    }
                }
            };
            _cartContext.Add(item);
            if(_cartContext.WriteData())
            {
                return Json(new {
                    message = "Thêm sản phẩm vào giỏ hàng thành công!",
                    position = "1"
                });
            }else
            {
                return Json(new {
                    message = "Không thể thêm sản phẩm vào giỏ hàng",
                    position = "0"
                });
            }
        }
    } 

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

web_bh/Controllers/CheckoutController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using web_bh.Models;

namespace web_bh.Controllers;

public class CheckoutController : Controller
{
    private readonly ILogger<CheckoutController> _logger;
    private readonly CartContext _cartContext;
    private readonly web_bhContext _context;

    public CheckoutController(ILogger<CheckoutController> logger, CartContext cartContext, web_bhContext context)
    {
        _logger = logger;
        _cartContext = cartContext;
        _context = context;
    }

    public IActionResult Index()
    {
        int? idUser = HttpContext.Session.GetInt32("user");
        if(idUser == null)
        {
            return RedirectToAction("Index", "Home");
        }else
        {
            var itemCart = _cartContext.cart.carts.Where(p => p.id_user == idUser).FirstOrDefault();
            int price = 0;
            if(itemCart != null)
            {
                var listCart = itemCart.cartItems.ToList();
                if(!listCart.Any())
                {
                    return RedirectToAction("Index", "Home");
                }
                foreach (var item in listCart)
                {
                    Product _tmp = _context.Products.Where(p => p.Id == item.id_product).FirstOrDefault();
                    if(_tmp != null)
                    {
                        price += _tmp.Price * item.quantity;
                    }
                }
            }else
            {
                return RedirectToAction("Index", "Home");
            }
            ViewData["price"] = price;
            return View();
        }
    }
    public async Task<JsonResult> CreateOrder(string fullName, string phone, string address, string note)
    {
        int? idUser = HttpContext.Session.GetInt32("user");
        if(idUser == null)
        {
            return Json(new {
                message = "Bạn phải đăng nhập mới sử dụng được chức năng này!",
                position = "0"
            });
        }else
        {
            var itemCart = _cartContext.cart.carts.Where(p => p.id_user == idUser).FirstOrDefault();
            if(itemCart == null || itemCart.cartItems == null)
            {
                return Json(new {
                    message = "Giỏ hàng trống không thể đặt hàng!",
                    position = "0"
                });
            }else
            {
                Order order = new Order();
                order.IdStatus = 1;
                order.IdUser = idUser;
                order.FullName = fullName;
                order.PhoneNumber = phone;
                order.Address = address;
                order.Note = note;
                order.OrderDate = DateTime.Now;

                _context.Add(order);
                await _context.SaveChangesAsync();

                var order_ = _context.Orders.Where(p => p == order).FirstOrDefault();
                if(order_ == null)
                {
                    return Json(new {
                        message = "Đã có lỗi xảy ra! Vui lòng thử lại!",
                        position = "0"
                    });
                }else
                {
                    foreach (var item in itemCart.cartItems.ToList())
                    {
                        Product prd = _context.Products.Where(p => p.Id == item.id_product).FirstOrDefault();
                        if(prd == null)
                        {
                            return Json(new {
                                message = "Lỗi sản phẩm không tồn tại! Vui lòng thử lại!",
                                position = "0"
                            });
                        }
                        prd.Quantity -= item.quantity;
                        _context.Update(prd);
                        OrderDetail orderDetail = new OrderDetail();
                        orderDetail.IdOrder = order_.Id;
                        orderDetail.IdProduct = item.id_product;
                        orderDetail.Num = item.quantity;
                        orderDetail.TotalMoney = prd.Price * orderDetail.Num;
                        _context.Add(orderDetail);
                        await _context.SaveChangesAsync();
                    }
                    _cartContext.Remove(itemCart);
                    _cartContext.WriteData();
                    return Json(new {
                        message = "Đặt hàng thành công!",
                        position = "1"
                    });
                }
            }
        }
    }
    public IActionResult Complate()
    {
        int? idUser = HttpContext.Session.GetInt32("user");
        if(idUser == null)
        {
            return RedirectToAction("Index", "Home");
        }else
        {
            return View("Complate");
        }
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

web_bh/Views/Checkout/Complate.cshtml
@{
    ViewData["Title"] = "Hoàn thành";
}
@section css {
<link rel="stylesheet" href="~/css/completeCheckout.css">
}
<h1>
    <img src="~/img/check_complete.png" alt="">
    <p>QUÝ KHÁCH ĐÃ ĐẶT HÀNG THÀNH CÔNG</p>
</h1>
<h3>
    <p>Cảm ơn quý khách đã đặt mua sản phẩm của chúng tôi !</p>
    <p>Đơn hàng của quý khách sẽ được nhân viên kiểm tra và giao hàng trong thời gian sớm nhất.</p>
</h3>
<a asp-controller="MyOrder" asp-action="Index">Xem đơn hàng</a>
<a asp-controller="Product" asp-action="Index">Tiếp tục mua sắm</a>

web_bh/Views/Checkout/Index.cshtml
@{
    ViewData["Title"] = "Thanh toán";
}
@section css {
<link rel="stylesheet" href="~/css/cart.css">
<link rel="stylesheet" href="~/css/checkout.css">
}
@section Scripts {
<script src="~/js/checkout.js"></script>
}
<div class="path">
    <a asp-controller="Home" asp-action="Index">Trang chủ </a>
    <a asp-controller="Checkout" asp-action="Index">| Thanh toán </a>
</div>
<div class="cart">
    <div class="checkout__body address">
        <h3>ĐỊA CHỈ ĐƠN HÀNG</h3>
        <h4>Họ tên</h4>
        <input type="text" id="fullName" placeholder="Họ và tên">
        <h4>Địa chỉ</h4>
        <input type="text" id="address" placeholder="Địa chỉ">
        <h4>Số điện thoại</h4>
        <input type="text" id="phone" placeholder="Số điện thoại">
        <h4>Lời nhắn</h4>
        <textarea name="" id="note" cols="30" rows="10"></textarea>
    </div>
</div>
<div class="right">
    <h3>HÌNH THỨC VẬN CHUYỂN</h3>
    <div class="checkout__body payment">
        <div>
            <input type="radio" name="shipping_" value="1" disabled>
            <h4> Vận chuyển nhanh ( 40,000 đ) (3-5 ngày) (hướng phát triển)</h4>
        </div>
        <div>
            <input type="radio" name="shipping_" value="2" checked>
            <h4> Vận chuyển miễn phí ( 0 đ) ( 10-15 ngày)</h4>
        </div>
    </div>
    <h3>HÌNH THỨC THANH TOÁN</h3>
    <div class="checkout__body payment">
        <div>
            <input type="radio" name="payment_" value="1" checked>
            <h4> Thanh toán khi nhận hàng</h4>
        </div>
        <div>
            <input type="radio" name="payment_" value="2" disabled>
            <h4> Thanh toán online (hướng phát triển)</h4>
        </div>
    </div>
    <h3>CHI PHÍ ĐƠN HÀNG</h3>
    <table>
        <tbody>
            <tr>
                <td>Giá trị đơn hàng</td>
                <td>
                    <p id="sum-price">@ViewBag.price</p>
                    <p> đ</p>
                </td>
            </tr>
            <tr>
                <td>Phí vận chuyển</td>
                <td>
                    <p id="shipping-price">0</p>
                    <p> đ</p>
                </td>
            </tr>
            <tr>
                <td>Thuế</td>
                <td>
                    <p id="tax">0</p>
                    <p>%</p>
                </td>
            </tr>
            <tr>
                <td>Tổng chi phí</td>
                <td>
                    <p id="price">@ViewBag.price</p>
                    <p> đ</p>
                </td>
            </tr>
        </tbody>
    </table>
</div>
<div class="cart__bottom">
    <a asp-controller="Cart">
        << Quay lại</a>
            <a id="complate">Hoàn thành ></a>
</div>